### ISSUE TITLE
LESSON-WIDE: Add "checkpoints" where learners should knit their document  (content/formatting)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#12]
to 1) see the syntax they added & 2) check for errors (content)

**Comment by torwhite** [comment]
Let's use the checklist formatting to indicate that it's time to knit (.checklist)

> ## Time to Knit
> to see x , y, z change
{: .checklist}

**Comment by rcurty** [comment]
Done for episodes 6 and 7. Added a few checkpoints for learners to knit and see how the markdown renders on html.

**Comment by rcurty** [comment]
done for episodes 3, 4, and 5 as well.

**Comment by torwhite** [comment]
code: 
> ## Time to Knit!
> Check how the table you have just created looks like. 
{: .checklist}

**Comment by torwhite** [comment]
added a checkpoint to ep. 11. Will add to ep. 9 and 10

**Comment by torwhite** [comment]
checkpoints added to episode 9 & 10
