### ISSUE TITLE
ep. 3: add a note about adding line breaks in rmd document (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#13]
Add a note right at the beginning before we even get into headings. blank lines will be required before  or before/after all headings, horizontal lines and lists.

You will need to make sure to add line breaks into your document or text will wrap when it renders (even if you hit enter/return and start typing on a new line in R studio)
You can add line breaks by using : 
- 2 enters/returns (leaving a blank line)
-  two spaces at the end of the line
- an html break <br>

These line breaks will also be important to get your formatting to render correctly. In some cases you MUST have a blank line (just two spaces or a break won't do the trick)

**Comment by torwhite** [comment]
add this right at the beginning before we even get into headings & lists.

**Comment by torwhite** [comment]
just because text is on the next line of the rmd, doesn't mean it's on a new line after knitting. 

use an `enter` or two spaces or a break `<br>

Now, if we were writing from scratch rather than copying and pasting text this probably wouldn't be an issue because we'd be adding enters/returns as we go....

**Comment by torwhite** [comment]
two spaces works, however I prefer enters so it's easier to read my rmd file while writing too.

**Comment by torwhite** [comment]
I'm going to enter at the end of lines ..., you can follow along with me to have a better sense of where the paragraphs are.

**Comment by torwhite** [comment]
7, end of 9, 16, 18, 20, 22, 24, 26, 29, 31, 33, 35, 37
(line #s change as you add enters so must be done in order)

(you'll notice headers (first level) are in all caps.)

**Comment by torwhite** [comment]
Honestly we should just add line breaks into the rest of the paper and maybe only demonstrate on the first couple lines. This will be time consuming

**Comment by serenaosmuss** [comment]
Added tip about blank lines before and after headings/horizontal lines/lists right before headings section
