### ISSUE TITLE
ep. 5 2nd figure needs to be left-aligned (formatting)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#17]
github centers automatically - but it should be left align to match rmd 

The example in rmd would still be left aligned

next piece is to learn how to center images so this doesn't make sense as is.

TODO: add left align to html code for the 2nd image that appears in episode 5.

**Comment by rcurty** [comment]
fixed...added html to align left to the first two images (not only the second).

**Comment by kristi-sara** [comment]
I got the image to align left but it puts the image on top of the challenge so nvm

**Comment by rcurty** [comment]
I will be trying a few more options

**Comment by torwhite** [comment]
Not necessary anymore considering we cannot center align with markdown.
