### ISSUE TITLE
ep. 1 timing 

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/R-markdown#21]
estimate 10 minutes instruction. 5 minutes for exercise

**Comment by torwhite** [comment]
I'm estimating 15-20 min, 8-10 min exercise

**Comment by rcurty** [comment]
estimate 15 min for instruction (since Greg will cover 3 examples of real-world applications) and 5 min for exercise (breakout room and discussion)

**Comment by ilessing** [comment]
we intend to record our actual timings and then close this issue.

**Comment by torwhite** [comment]
This episode took 23 min during the December 16/17 workshop.
