### ISSUE TITLE
ep. 2: format challenge 2.1

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/R-markdown#22]
It does not have the challenge style applied. Syntax is:

> ## CHALLENGE 3.1
> Insert headings throughout the rest of the paper so it is split into 5 sections (Introduction, Materials and Methods, Results and Discussion, Conclusion, and References). Use the search function in R Markdown to find these lines in the document. 
>
>> ## SOLUTION
>> ```
>> ## INTRODUCTION
>> ## MATERIALS AND METHODS
>> ## RESULTS AND DISCUSSION
>> ## CONCLUSION
>> ## REFERENCES
>> ```
>> Why are we using `##`? Because `#` should only be used once in the paper (for the title) and `##` is for the next heading level.
> {: .solution}
{: .challenge}

**Comment by torwhite** [comment]
Again, formatting was present, rendering was off. Closing.
