### ISSUE TITLE
ep. 2: more explicit help for basic formatting (content)

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/R-markdown#25]
After the header '2. Formatted text'

In the paragraph it says "Notice you don’t need to use # to comment out narrative. You also don’t need to encase the text in any symbols as you do code chunks."

Both of these assume a lot of knowledge. Consider making it newb friendly:

As you might know, in a regular R file, # starts a comment. In R markdown, plain text is just plain narrative text that appears in the document.  In R scripts, plain text wants to be code. In R markdown, you will need to enclose your code in special characters ```

**Comment by rcurty** [comment]
done
