### ISSUE TITLE
ep 2 -Install Packages: Knitr & KableExtra (content)

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/R-markdown#27]
Remove the reference about installing kable in episode 2. 

Kable is  listed as a necessary package to download but it is a function within the Knitr package so learners need to install or update knitr to use it. 

<img width="282" alt="oh look" src="https://user-images.githubusercontent.com/48770663/101226559-b315e080-3649-11eb-8a2a-1165d5c4360b.PNG">

<img width="457" alt="oof" src="https://user-images.githubusercontent.com/48770663/101226570-b8732b00-3649-11eb-9df8-74672cd68724.PNG">

@torwhite

**Comment by jonjab** [comment]
Consider changing challenge 2.2 to install bookdown, tidyverse, knitr, and kableExtra.

**Comment by kristi-sara** [comment]
changed packages to knitr and kableExtra. 
https://github.com/UCSBCarpentry/R-markdown/commit/d1849eee6c168ed88aa7d1c3394a8febc09c685f

**Comment by torwhite** [comment]
WAIT until it's verified we need to use the KableExtra package. If we don't need it, we shouldn't have learners install it.

**Comment by torwhite** [comment]
took out kableExtra, it will be mentioned, but not used.
