### ISSUE TITLE
ep. 2: specify an output folder (content)

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/R-markdown#28]
the lesson sets up the folder structure for our project, but we don't give any guidance on where to put knit html file.  Specify the 'results' folder as early as possible.

**Comment by torwhite** [comment]
the output folder is always the same folder as the .Rmd document. We will show people how to change that at the end of the workshop but it takes some more difficult coding. 

Add note that this will be covered in final episode 11.
