### ISSUE TITLE
ep. 2 challenge 2.3 reword challenge (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#32]
Challenge text: "Can you deduce what each of the three types of symbols (##, **, <>) do for formatting?"

Change to:

In Rmd certain symbols are used to denote formatting that should happen to the text (after we "knit" or render). Before we knit, these symbols will show up seemingly "randomly" throughout the text and don't contribute to the narrative in a logical way. In the generic Rmd document, there are three types of such symbols (##, **, <>) .  Each symbol represents a different kind of formatting (think of your text formatting buttons you use in Word). Can you deduce from the surrounding text how these symbols format the surrounding text?

(or something like that)

**Comment by rcurty** [comment]
Changed
