### ISSUE TITLE
ep. 3 Numbered section example should be .source callout (formatting)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#36]
This: 
---
title: "An Adapted Survey on Scientific Shared Resource Rigor and Reproducibility"
author: Add Your Name Here
date: "December 15, 2020"
output:
  html_document:
    number_sections: true

should be code callout {: .source} to indicate it's something we're adding to our paper rmd file.

**Comment by torwhite** [comment]
Serena, it's okay if you can't figure this one out or don't have time for it.

**Comment by serenaosmuss** [comment]
I think I've got the formatting updated here
