### ISSUE TITLE
ep. 3 combine challenges 3.1 & 3.2 (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#37]
I think it makes sense to combine them. It's clunky to add all heading 1s THEN introduce another challenge to add heading 2s. Introduce them both at once so learners can work through the challenges in their preferred order (we'll just have to give them more time to complete since it will be a two part challenge.

Format for challenge box

1. Add all section headers (#):
(list sections)
2. Add all sub section headers (##)
(list sub-section headers)

**Comment by serenaosmuss** [comment]
combined adding all headings and subheadings into challenge 3.1
