### ISSUE TITLE
ep. 3 add horizontal lines to our paper? (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#39]
horizontal lines are demonstrated but not carried out in paper. 

Let's add a horizontal line right at the beginning of the paper (so it appears under the title)

---
(Let's leave this out before the workshop, we can consider adding it for the next time it's taught) :
Optional: challenge to add lines after each section header?

**Comment by serenaosmuss** [comment]
added optional challenge in horizontal lines section
