### ISSUE TITLE
ep. 3 Challenge 3.3 word to search (formatting)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#41]
Have them search "it is important to highlight:" Replace the following text with a bullet point (3) for each sentence. 

I was confused for a second and thought the bullets would start after "At least 170" but that's where the first bullet should be.

**Comment by rcurty** [comment]
Improved to "Now let’s practice creating bullet lists. Search in the paper "it is important to highlight:" and apply bullet points for each of the next 3 sentences"
