### ISSUE TITLE
ep. 3/setup edit paper-raw.txt for challenge 3.4

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#42]
The raw text contains extra commas and an "and" . Take those out OR have learners delete the commas & and as part of the challenge. the commas might be good to signal a new numbered item (but then add this in to challenge as an indicator). whichever is easier.

**Comment by torwhite** [comment]
Also, learners will need to add a line break after "follows:", and each numbered item.

We COULD let them figure that as part of the challenge since they will have learned line breaks already.

**Comment by torwhite** [comment]
let's let them figure out the line break, but let's take out the commas & "and" before sending the setup files.

**Comment by rcurty** [comment]
removed commas and the end
