### ISSUE TITLE
ep. 4: can't find "Springer" (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#45]
I.e. We want to italicize Springer’s name. Find where we reference the survey and change Springer to Springer by putting either asterisks or underscores around the name (*Springer* or _Springer_).

may have been removed when we changed the citation prompts?

**Comment by torwhite** [comment]
we can probably just get rid of this example because Springer will be a citation anyway.

**Comment by rcurty** [comment]
Removed.
