### ISSUE TITLE
ep. 4 Why are we teaching &quot;?? (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#46]
Why are we teaching `&quot;`? Regular quotes work just fine. 

Would be better to teach blockquotes.

**Comment by torwhite** [comment]
Is there a good reason we're learning `&quot;`? needs to be added to the episode then.

**Comment by rcurty** [comment]
Removed challenges and examples.

**Comment by torwhite** [comment]
I'm just noting this because it's interesting and for no other reason, but straight quotes "" are rendered as curly quotes in the html after knitting.
