### ISSUE TITLE
ep. 4 Add to challenge italics & bold (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#47]
The whole emphasis section feels weird. We learn italics, bold and quotes but the one italics example doesn't work and the whole challenge is add `&quot;` which is indistinguishable from a regular `"` anyway. 

Add spots to add italics & bold.

**Comment by rcurty** [comment]
I have added spots to add italics and bold in the lesson and the paper example. I did not use the challenge format though, should I?

**Comment by rcurty** [comment]
added a challenge
