### ISSUE TITLE
ep. 4 Format hyperlinks correctly (formatting)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#48]
In adding symbols & formulas section

https://www.overleaf.com/learn/latex/Mathematical_expressions
The canonical LaTeX reference, written by the author (hardback, but viewable online):

https://archive.org/details/latex00lesl
https://ucsb-primo.hosted.exlibrisgroup.com/permalink/f/1egv95m/01UCSB_ALMA21230090630003776

**Comment by rcurty** [comment]
done
