### ISSUE TITLE
ep. 4 What symbols can be added other than formulas? (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#49]
We learn formulas but not symbols other than what is used in formulas

**Comment by rcurty** [comment]
Agreed. At this point should we remove symbols from the lesson title, section, questions, and objectives, or come up with new content and examples explaining symbols?
@gjanee @torwhite

**Comment by torwhite** [comment]
I think that makes sense. Let's leave it as Emphasis & formulas
