### ISSUE TITLE
ep. 2: where to save your document

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/R-markdown#53]
Where are we keeping the marked-down version of our paper? ep. 2 doesn't say, I don't think. 

The screenshot has it appearing to go into "My Documents", but that's not a great place to save our work.

In the root of our project folder? In the docs folder?

**Comment by kristi-sara** [comment]
zipped PapertoRmd folder save desktop > and save work in the data folder inside (torin will do)

**Comment by torwhite** [comment]
Rmd should be saved to the `code` sub folder of the setup folder. this prompt has been added in ep. 2 under "Try it Yourself"
