### ISSUE TITLE
Ep. 5: Add short blurb on relative paths (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#58]
We can't assume people will understand relative paths. 

Explain `.`, `..` and `/` for navigating folder levels.

**Comment by torwhite** [comment]
ALSO talk about setting the working directory. (and figuring out what your working directory currently is)

**Comment by rcurty** [comment]
@torwhite I am looking at issue #58. I agree we should include some instruction about the relative path, but perhaps getting that covered in episode 5 will be too distracting. Any room to cover that in ep. 2  in good practices for organizing and then briefly reiterate it in ep. 5 when learners will have to include the path to images? Same for working directory.

**Comment by rcurty** [comment]
Thinking to use a summary version of this explanation https://ssc.wisc.edu/sscc/pubs/R_intro/book/1-10-paths-and-working-directories.html

**Comment by rcurty** [comment]
I have added a tip box, but won't close this issue until reviewed.

**Comment by jonjab** [comment]
that tip box looks good tome.
