### ISSUE TITLE
SETUP: edit paper_raw txt so that all table row are on the same line (formatting)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#61]
**for example:**
Category
N
Poor sample quality from users/sample variability/limited biological material
51

Lack of well-trained principle investigators and lab members/Poor oversight
45
Poor experimental design: Lack of sufficient replicates/inadequate sample size/lack of adequate controls
43

**should be :**

Category N
Poor sample quality from users/sample variability/limited biological material 51

Lack of well-trained principle investigators and lab members/Poor oversight 45
Poor experimental design: Lack of sufficient replicates/inadequate sample size/lack of adequate controls 43

**Comment by rcurty** [comment]
fixed
