### ISSUE TITLE
ep. 5: Fix file paths for figs (formatting)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#62]
Everyone should set working directory as: paperToRmd or whatever we name the lesson zip folder download.

Then, 

figs should be: 

../figs/figure1_paper.jpg

**Comment by torwhite** [comment]
ADD to lesson:

A preview of your image should pop up automatically if you have the correct relative path.

**Comment by rcurty** [comment]
solved
