### ISSUE TITLE
SETUP/ ep. 5: Captions get duplicated (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#63]
Delete captions from paper_raw. 

Have learners add figures after the (Fig. 1) "landmarks" rather than before the caption because the caption is in the image information too so the captions get displayed twice when knitting.

**Comment by torwhite** [comment]
make sure issues #59 and #57 are executed accordingly.

**Comment by rcurty** [comment]
done.
