### ISSUE TITLE
ep. 6: Fix formatting Github markdown footnotes (formatting)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#64]
We can add footnotes to our paper using the ^ symbol. Similar to adding emphasis, putting carrot symbols around your text will print the output as a superscript.

superscript^1^ will **give output: superscript^1^**

the bolded piece does not output with footnotes in Github markdown.

**Comment by rcurty** [comment]
I had to use the <sup> tag to render correctly on Github. Works fine now.
