### ISSUE TITLE
SETUP: line breaks in paper_raw (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#74]
It would be easier for learners if the line breaks were already in the document so they don't have to add them as we go (also makes it easier to read the document). In the second half of the paper the spacing is fine but the first  half not so much. I propose having no line breaks for the first paragraph or so (so we can demonstrate adding them) but after that have them added to the document already:

line breaks to add (review):
7, end of 9, 16, 18, 20, 22, 24, 26, 29, 31, 33, 35, 37
(line #s change as you add enters so must be done in order)

**Comment by rcurty** [comment]
done
