### ISSUE TITLE
ep. 5 Add example of blockquote (pull quote) (content)

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#77]
We just want to demonstrate a pull quote here (or emphasizing a part of the text)

There will be another example in ep. 7 (of a long quote requiring citation)

**Comment by rcurty** [comment]
Done on episode 7 (example of a long citation). Also added a new one for the emphasis part (current episode 4) 
_I have seen further it is because I have stood on the shoulders of giants_ (Isaac Newton). Both papers (raw and template were updated as well)
