### ISSUE TITLE
Challenges (Titles)

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/R-markdown#80]
Some challenges have only numbers (ep. 2), others have titles. Perhaps add a short description to all...it also helps instructors to situate themselves.

**Comment by torwhite** [comment]
agreed, numbers & short titles is ideal.

**Comment by rcurty** [comment]
Titles added 2-9 (except for 9.3 which has a FIXME). Check for Episodes 10 and 11 when finalized.

**Comment by torwhite** [comment]
added to 9. will add to 10 where applicable, but I don't think 11 will have challenges. 

closing this.
