### ISSUE TITLE
ep. 5 Paths

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/R-markdown#85]
Fix paths to images. Oddly the original figs path is not previewing nor rendering images as it used to. It works when we use the general fig folder though.

**Comment by rcurty** [comment]
the solution has figs, but all html to display in md are using the fig folder path instead.

**Comment by rcurty** [comment]
We will be sharing the figs folder with learners not the fig including all the lessons screenshots, correct?

**Comment by torwhite** [comment]
correct. So learners will have to use images in the "figs" folder of their project folder download.

**Comment by torwhite** [comment]
I will take a look at the file paths in ep. 5

**Comment by torwhite** [comment]
the path needs to be "../figs/[image file] for learners

**Comment by torwhite** [comment]
fixed in episode Rmd

**Comment by torwhite** [comment]
In regards to the actual issue, images only preview if you type the code out by hand (not copying/pasting)

https://github.com/rstudio/rstudio/issues/4087
