### ISSUE TITLE
Rendered episodes will not show output callout correctly for markdown syntax examples

### ISSUE THREAD

**Issue by torwhite** [UCSBCarpentry/R-markdown#9]
For some reason, using the {: .output} with markdown syntax causes the callout to break.

If we want the intended outputs to display in the output callout we will need to grab a screenshot of the correct from r studio if we want to display how it should look after rendering the rmd

Other solution: just don't use callouts. However, callouts for code (r-language) and output will indicated to learners and instructors where they should be making edits to the paper.

**Comment by torwhite** [comment]
For instance this code:

\> \# MATERIALS AND METHODS  
\> \## Survey Overview  
\> \## Data Analysis  
{: .output}

outputs the following:

![image](https://user-images.githubusercontent.com/58574172/100391095-47979780-2fe7-11eb-9ae7-09e5d465f494.png)

**Comment by ilessing** [comment]
for reference: https://carpentries.github.io/lesson-example/04-formatting/index.html#formatting-code

**Comment by ilessing** [comment]
would surrounding the code block with three tildes achieve the desired effect?
example:
```
~~~
> # MATERIALS AND METHODS
> ## Survey Overview
> ## Data Analysis
~~~
{: .output}
```

**Comment by torwhite** [comment]
No, I've tried that too, the callout works properly, but any markdown that is between ~~~ ~~~s doesn't render as markdown.

![image](https://user-images.githubusercontent.com/58574172/100487472-a3cceb00-30bd-11eb-99ae-c367ddd0945a.png)
* Don't mind the mismatched #s, this was just for experimentation's sake.

My solution was just not to render markdown in the answers. For this example it's fine, we will just have the code box for what need's to be edited in the rmd file:

![image](https://user-images.githubusercontent.com/58574172/100487519-e42c6900-30bd-11eb-9bca-68063b04a6ae.png)

For challenges, it makes sense to have the "solution" be the un-rendered markdown syntax. The challenge we're asking them to "solve" is what markdown do you use? Not what does it look like when rendered?

![image](https://user-images.githubusercontent.com/58574172/100487570-38374d80-30be-11eb-81d3-9bc8093f8a25.png)

the markdown code in solutions does need to be between \``` \``` s to display correctly.

**Comment by torwhite** [comment]
For formatting & consistency's sake, we should :
1) for examples that don't need to be input to the paper example rmd file, DON'T use `{: .source}` callouts but DO use  \``` \``` so the markdown doesn't render. For short partial line chunks ` ` can be used. 
2) use `{: .source}` callouts for code we're walking them through to add to the rmd file.
3) for challenge solutions the solutions should be unrendered markdown syntax between \``` \```

Examples: 
1) **R markdown examples**
code: 
![image](https://user-images.githubusercontent.com/58574172/100487984-54d48500-30c0-11eb-9a35-0705f9c5e15d.png)
*I can't get the markdown to render correctly this this comment so this is just a screenshot

outputs to:
![image](https://user-images.githubusercontent.com/58574172/100487875-b3e5ca00-30bf-11eb-98a8-554a7eb081bd.png)

2) **Paper edits (not challenges)**
code: 
```
~~~
## MATERIALS AND METHODS  
### Survey Overview  
### Data Analysis  
~~~
{: .source}
```
outputs as: 
![image](https://user-images.githubusercontent.com/58574172/100487796-55b8e700-30bf-11eb-8925-52fad5db9c18.png)

3) **Paper edits (challenges)**
code: 
```
> ## CHALLENGE 3.1
> Insert headings throughout the rest of the paper so it is split into 5 sections (Introduction, Materials and Methods, Results and Discussion, Conclusion, and References). Use the search function in R Markdown to find these lines in the document. 
>
>> ## SOLUTION
>> ```
>> ## INTRODUCTION
>> ## MATERIALS AND METHODS
>> ## RESULTS AND DISCUSSION
>> ## CONCLUSION
>> ## REFERENCES
>> ```
>> Why are we using `##`? Because `#` should only be used once in the paper (for the title) and `##` is for the next heading level.
> {: .solution}
{: .challenge}
```
outputs as:
![image](https://user-images.githubusercontent.com/58574172/100487815-6e290180-30bf-11eb-8e54-c4f97dfb39be.png)
